# GitHub Sponsors funding options for LodeX Studio

# These are supported funding model platforms

# GitHub Sponsors (if you set up)
# github: lodsa-ntos

# Custom funding URLs
custom: ['https://lodexstudio.com/conversar', 'mailto:lodexstudio@gmail.com']
